USE LOCADORA;
GO

SELECT * FROM EMPRESA;
SELECT * FROM CLIENTE;
SELECT * FROM MARCA;
SELECT * FROM MODELO;
SELECT * FROM VEICULO;
SELECT * FROM ALUGUEL;



SELECT dataRetirada, dataDevolucao, CLIENTE.nomeCliente, MODELO.nomeModelo FROM ALUGUEL
LEFT JOIN CLIENTE
ON ALUGUEL.idcliente = CLIENTE.idCliente
LEFT JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
LEFT JOIN MODELO
ON VEICULO.idModelo = MODELO.idModelo;


                    
SELECT nomeCliente, dataRetirada, dataDevolucao, MODELO.nomeModelo FROM CLIENTE
LEFT JOIN ALUGUEL
ON CLIENTE.idCliente = ALUGUEL.idCliente
LEFT JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
LEFT JOIN MODELO
ON VEICULO.idModelo = MODELO.idModelo;