
CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

DROP DATABASE LOCADORA;
GO

USE MASTER;
GO

CREATE TABLE EMPRESA (
	idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE CLIENTE (
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(30) NOT NULL,
	sobrenomeCliente VARCHAR(100) NOT NULL,
	CNH CHAR(11) NOT NULL
);
GO

CREATE TABLE MARCA (
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MODELO (
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
	nomeModelo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE VEICULO (
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	placa VARCHAR(8) NOT NULL
);
GO

CREATE TABLE ALUGUEL (
	idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	dataRetirada DATE NOT NULL,
	dataDevolucao DATE NOT NULL
);
GO
