
CREATE DATABASE CLINICA;
GO

DROP DATABASE CLINICA;
GO

USE CLINICA;
GO

CREATE TABLE CLINICA (
	idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(30) NOT NULL,
	cnpj CHAR(14) NOT NULL UNIQUE,
	endereco VARCHAR(40) NOT NULL
);
GO

CREATE TABLE VETERINARIOS (
	idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
	idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
	CRMV CHAR(14) NOT NULL UNIQUE,
	nome VARCHAR(30) NOT NULL
);
GO

CREATE TABLE DONO (
	idDono TINYINT PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(30) NOT NULL
);
GO

CREATE TABLE PETS (
	idPet TINYINT PRIMARY KEY IDENTITY(1,1),
	idDono TINYINT FOREIGN KEY REFERENCES DONO(idDono),
	nome VARCHAR(30) NOT NULL,
	dataNascimento SMALLDATETIME NOT NULL,
	idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet)
);
GO

CREATE TABLE TIPOPET (
	idTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoPet VARCHAR(200) UNIQUE
);
GO

CREATE TABLE RACA (
	idRaca TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
	nomeRaca VARCHAR(200) UNIQUE
);
GO

CREATE TABLE CONSULTA (
	idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIOS(idVeterinario),
	idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
	idConsulta SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPet TINYINT FOREIGN KEY REFERENCES PETS(idPet),
	dataConsulta SMALLDATETIME NOT NULL,
	descricaoConsulta VARCHAR(2000)
);
GO