USE CLINICA;
GO

SELECT * FROM CLINICA;
SELECT * FROM VETERINARIOS;
SELECT * FROM DONO;
SELECT * FROM PETS;
SELECT * FROM TIPOPET;
SELECT * FROM RACA;
SELECT * FROM CONSULTA;



SELECT nome, CRMV, nomeClinica FROM VETERINARIOS
INNER JOIN CLINICA
ON VETERINARIOS.idClinica = CLINICA.idClinica
WHERE CLINICA.idClinica = 1;


SELECT * FROM RACA
WHERE nomeRaca LIKE 's%';


SELECT * FROM TIPOPET
WHERE nomeTipoPET LIKE '%o';


SELECT idPet, PETS.nome, dataNascimento AS [Data Nascimento], DONO.nome AS [Nome Dono] FROM PETS
LEFT JOIN DONO
ON PETS.idDono = DONO.idDono;


SELECT idConsulta, VETERINARIOS.nome [Veterinário], PETS.nome pet, RACA.nomeRaca [raça], TIPOPET.nomeTipoPet [espécie], DONO.nome, nomeClinica FROM CONSULTA
LEFT JOIN VETERINARIOS
ON CONSULTA.idVeterinario = VETERINARIOS.idVeterinario
INNER JOIN PETS
ON CONSULTA.idPET = PETS.idPet
INNER JOIN RACA
ON PETS.idRaca = RACA.idRaca
INNER JOIN TIPOPET
ON RACA.idTipoPet = TIPOPET.idTipoPet
INNER JOIN DONO
ON PETS.idDono = dono.idDono
INNER JOIN CLINICA
ON VETERINARIOS.idClinica = CLINICA.idClinica;