CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE USUARIO (
	idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeUsuario VARCHAR(30) NOT NULL,
	emailUsuario VARCHAR(256) NOT NULL,
	senha VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ARTISTA (
	idArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeArtista VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ESTILO (
	idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEstilo VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ALBUM (
	idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
	nomeAlbum VARCHAR(30) NOT NULL,
	dataLancamento SMALLDATETIME NOT NULL
);
GO

CREATE TABLE ESTILOALBUM (
	idEstiloAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo)
);
GO