
CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA (
	idEmpresa TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE CLIENTE (
	idcliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MARCA (
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(30) NOT NULL
);
GO

CREATE TABLE VEICULO (
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	placa TINYINT NOT NULL
);
GO

CREATE TABLE MODELO (
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	nomeModelo VARCHAR(20) NOT NULL
);
GO

ALTER TABLE VEICULO
ADD idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo)


CREATE TABLE ALUGUEL (
	idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idcliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idcliente),
	dataDevolucao DATE NOT NULL
);
GO
