CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

DROP DATABASE OPTUS;
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeUsuario VARCHAR(30) NOT NULL,
	emailUsuario VARCHAR(256) NOT NULL,
	senha VARCHAR(30) NOT NULL,
	permissaoAcesso VARCHAR(14) NOT NULL
);
GO

CREATE TABLE ARTISTA (
	idArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeArtista VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ESTILO (
	idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEstilo VARCHAR(30) NOT NULL
);
GO

CREATE TABLE ALBUM (
	idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
	nomeAlbum VARCHAR(30) NOT NULL,
	dataLancamento SMALLDATETIME NOT NULL,
	localizacaoAlbum VARCHAR(150) NOT NULL,
	tempoAlbumMinutos TINYINT NOT NULL,
	AtivoVisualizacao VARCHAR(3) NOT NULL,
	idEstiloAlbum SMALLINT FOREIGN KEY REFERENCES ESTILOALBUM(idEstiloAlbum)
);
GO

CREATE TABLE ESTILOALBUM (
	idEstiloAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo)
);
GO